_auth/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from _auth.constants import URLS
from _auth.forms import LoginForm
from _homepage.constants import URLS as HOMEPAGE_URLS

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': '_auth/login.html', 'authentication_form': LoginForm},
        name=URLS.SIGN_IN),
    url(r'^logout/$', auth_views.logout, {'next_page': HOMEPAGE_URLS.HOMEPAGE}),
    url(r'^sing_up/$', views.sign_up, name=URLS.SIGN_UP),
    url(r'^password_reset/$', auth_views.password_reset,
        {'template_name': '_auth/password_reset.html', 'post_reset_redirect': URLS.PASSWORD_RESET_REDIRECT},
        name=URLS.PASSWORD_RESET),

    url(r'^password_reset/done$', views.password_reset_done, name=URLS.PASSWORD_RESET_REDIRECT),
    url(r'^profile/(.*)/$', views.profile, name=URLS.PROFILE),
    url(r'^my_profile/$', views.my_profile, name=URLS.MY_PROFILE),
    url(r'^my_profile/edit$', views.my_profile_edit, name=URLS.MY_PROFILE_EDIT),
]

_questions/urls.py
from django.conf.urls import url

from . import views
from _questions.constants import URLS


urlpatterns = [
    url(r'^questions/administration$', views.administration, name=URLS.ADMINISTRATION),
    url(r'^questions/$', views.questions, name=URLS.QUESTIONS),
    url(r'^questions/grid_data$', views.questions_grid_data, name=URLS.QUESTIONS_GRID_DATA),
    url(r'^questions/ask_question$', views.ask_question, name=URLS.ASK_QUESTION),
    url(r'^questions/(.*)/(.*)$', views.view_question, name=URLS.VIEW_QUESTION),
    url(r'^question/(.*)/edit$', views.edit_question, name=URLS.EDIT_QUESTION),
    url(r'^question/(.*)/revision$', views.authorize_question_edit, name=URLS.AUTHORIZE_QUESTION_EDIT),
    url(r'^question/add_comment$', views.question_add_comment, name=URLS.COMMENT_QUESTION),
    url(r'^question/(.*)/scrap$', views.question_scrap, name=URLS.SCRAP_QUESTION),
    url(r'^question/(.*)/scrap_comment$', views.question_comment_scrap, name=URLS.SCRAP_QUESTION_COMMENT),
    url(r'^answer/(.*)/edit$', views.edit_answer, name=URLS.EDIT_ANSWER),
    url(r'^answer/(.*)/revision/$', views.authorize_answer_edit, name=URLS.AUTHORIZE_ANSWER_EDIT),
    url(r'^answer/add_comment$', views.answer_add_comment, name=URLS.COMMENT_ANSWER),
    url(r'^answer/(.*)/scrap$', views.answer_scrap, name=URLS.SCRAP_ANSWER),
    url(r'^answer/(.*)/scrap_comment$', views.answer_comment_scrap, name=URLS.SCRAP_ANSWER_COMMENT),
    url(r'^tags/find$', views.find_tags, name=URLS.FIND_TAGS),
    url(r'^tags/create$', views.create_tag, name=URLS.CREATE_TAG),
    url(r'^vote/question/(.*)/up$', views.vote_up_question, name=URLS.VOTE_UP_QUESTION),
    url(r'^vote/question/(.*)/down$', views.vote_down_question, name=URLS.VOTE_DOWN_QUESTION),
    url(r'^vote/answer/(.*)/up$', views.vote_up_answer, name=URLS.VOTE_UP_ANSWER),
    url(r'^vote/answer/(.*)/down$', views.vote_down_answer, name=URLS.VOTE_DOWN_ANSWER),
]

pochopit/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('_homepage.urls')),
    url(r'^', include('_auth.urls')),
    url(r'^', include('_courses.urls')),
    url(r'^', include('_components.urls')),
    url(r'^', include('_questions.urls')),
    url(r'^', include('_messages.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^djangojs/', include('djangojs.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]

_questions/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    STATUS_ACTIVE = 0
    STATUS_DELETED = 1

    user = models.ForeignKey(User)
    title = models.CharField(max_length=254)
    text = models.TextField()
    votes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    scrap = models.IntegerField(default=0)
    paid = models.BooleanField(default=False)
    status = models.IntegerField(default=STATUS_ACTIVE)
    created = models.DateTimeField(auto_now_add=True)

    def has_active_revision(self, user):
        return self.questionrevision_set.filter(status=QuestionRevision.STATUS_AWATING_APPROVAL).exclude(
            editor=user).count() > 0


class QuestionRevision(models.Model):
    STATUS_AWATING_APPROVAL = 0
    STATUS_APPROVED = 1
    STATUS_REJECTED = 2

    question = models.ForeignKey(Question)
    editor = models.ForeignKey(User)
    supervisor = models.ForeignKey(User, default=0, related_name='supervisor')
    title = models.CharField(max_length=254)
    text = models.TextField()
    tags = models.ManyToManyField('Tag')
    editor_comment = models.TextField()
    supervisor_comment = models.TextField()
    sophistication = models.IntegerField(default=0)
    status = models.IntegerField(default=STATUS_AWATING_APPROVAL)
    created = models.DateTimeField(auto_now_add=True)


class QuestionComment(models.Model):
    question = models.ForeignKey(Question)
    user = models.ForeignKey(User)
    text = models.TextField()
    scrap = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)


class QuestionScrap(models.Model):
    question = models.ForeignKey(Question)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)


class QuestionCommentScrap(models.Model):
    question_comment = models.ForeignKey(QuestionComment)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)


class Answer(models.Model):
    question = models.ForeignKey(Question)
    user = models.ForeignKey(User)
    text = models.TextField()
    votes = models.IntegerField(default=0)
    paid = models.BooleanField(default=False)
    scrap = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    def has_active_revision(self, user):
        return self.answerrevision_set.filter(status=AnswerRevision.STATUS_AWATING_APPROVAL).exclude(
            editor=user).count() > 0


class AnswerRevision(models.Model):
    STATUS_AWATING_APPROVAL = 0
    STATUS_APPROVED = 1
    STATUS_REJECTED = 2

    answer = models.ForeignKey(Answer)
    editor = models.ForeignKey(User)
    supervisor = models.ForeignKey(User, default=0, related_name='answer_rev_supervisor')
    text = models.TextField()
    editor_comment = models.TextField()
    supervisor_comment = models.TextField()
    sophistication = models.IntegerField(default=0)
    status = models.IntegerField(default=STATUS_AWATING_APPROVAL)
    created = models.DateTimeField(auto_now_add=True)


class AnswerComment(models.Model):
    answer = models.ForeignKey(Answer)
    user = models.ForeignKey(User)
    text = models.TextField()
    scrap = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)


class AnswerScrap(models.Model):
    answer = models.ForeignKey(Answer)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)


class AnswerCommentScrap(models.Model):
    answer_comment = models.ForeignKey(AnswerComment)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    user = models.ForeignKey(User)
    questions = models.ManyToManyField(Question)
    title = models.CharField(max_length=254)
    description = models.TextField()


class VoteQuestion(models.Model):
    question = models.ForeignKey(Question)
    user = models.ForeignKey(User)
    up = models.BooleanField()
    mits = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)


class VoteAnswer(models.Model):
    answer = models.ForeignKey(Answer)
    user = models.ForeignKey(User)
    up = models.BooleanField()
    mits = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

_questions/views.py
from functools import reduce
import datetime
import bleach
from django.contrib import messages

from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from _messages.models import Message
from _messages.utils import MessageUtil
from _questions.constants import URLS, PERMISSION, PERMISSION_GROUPS
from _questions.forms import QuestionForm, TagForm, AnswerForm, QuestionEditForm, AnswerEditForm, \
    QuestionRevisionForm, AnswerRevisionForm
from _questions.models import Question, Tag, Answer, VoteQuestion, VoteAnswer, QuestionRevision, AnswerRevision, \
    QuestionComment, AnswerComment, QuestionScrap, AnswerScrap, AnswerCommentScrap, QuestionCommentScrap
from django.utils.translation import ugettext as _
from pochopit import constants
from pochopit.app_util import AppUtil
from pochopit.models import MitTransaction

QUESTION_SCRAP_LIMIT = 5
ANSWER_SCRAP_LIMIT = QUESTION_SCRAP_LIMIT


def questions(request):
    if 'q' in request.GET:
        search_query = bleach.clean(request.GET['q'], tags=[], strip=True)
    else:
        search_query = ''

    if request.user.is_authenticated():
        user_is_supervisor = get_user(request).groups.filter(name=PERMISSION_GROUPS.SUPERVISOR).exists()
    else:
        user_is_supervisor = False

    return render(request, '_questions/questions.html',
                  {'search_query': search_query, 'user_is_supervisor': user_is_supervisor})


def questions_grid_data(request):
    # todo vyladit dotaz tak, aby skutecne vracel relevanti vysledky
    offset = int(request.POST['offset'])
    if 'q' in request.POST:
        search_list = request.POST['q'].split(' ')
        question_list = Question.objects.filter(
            reduce(lambda x, y: x | y, [Q(title__contains=item) for item in search_list])).exclude(
            scrap__gt=5).order_by('-created')[offset:offset + 10]
    else:
        question_list = Question.objects.exclude(scrap__gt=QUESTION_SCRAP_LIMIT).order_by('-created')[
                        offset:offset + 10]

    return render(request, '_questions/question.html', {'question_list': question_list})


@login_required
def ask_question(request):
    tags = []
    if request.method == 'POST':
        question = Question()
        question.user = get_user(request)
        added_tags_ids = filter(None, request.POST['added_tags'].split(';'))
        tags = Tag.objects.filter(id__in=added_tags_ids)
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            question.tag_set = tags
            question.save()
            url = reverse(URLS.QUESTIONS)
            return HttpResponseRedirect(url)
    else:
        form = QuestionForm()

    return render(request, '_questions/question_form.html', {'form': form, 'tags': tags})


# noinspection PyUnusedLocal
def view_question(request, question_id, question_title):
    question = Question.objects.get(id=question_id)
    user = get_user(request)
    show_answer_input = False

    if request.user.is_authenticated():
        show_answer_input = question.user_id != user.id and question.answer_set.filter(user=user).count() == 0

    if request.user.is_authenticated() and request.method == 'POST':
        answer = Answer()
        answer.user = user
        answer.question = question
        form = AnswerForm(request.POST, instance=answer)
        if show_answer_input is False:
            messages.add_message(request, messages.ERROR, _('You can add only one answer to question!'))
        else:
            if form.is_valid():
                form.save()
                MessageUtil.send_message(user, question.user, Message.TYPE_NEW_ANSWER, params=question.id)
                url = reverse(URLS.VIEW_QUESTION, args=(question.id, question.title.replace(' ', '-')))
                return HttpResponseRedirect(url)
    else:
        question.views += 1
        question.save()
        form = AnswerForm()

    answer_set = question.answer_set.exclude(scrap__gt=ANSWER_SCRAP_LIMIT)
    auth_question_edit = user.has_perm(PERMISSION.AUTHORIZE_QUESTION_EDIT)
    auth_answer_edit = user.has_perm(PERMISSION.AUTHORIZE_ANSWER_EDIT)
    return render(request, '_questions/question_detail.html',
                  {'question': question, 'form': form, 'show_answer_input': show_answer_input, 'answer_set': answer_set,
                   'authorize_question_edit': auth_question_edit, 'authorize_answer_edit': auth_answer_edit})


@login_required
def edit_question(request, question_id):
    question = Question.objects.get(id=question_id)
    tags = question.tag_set.all()
    prev_revision = None
    question_revision = QuestionRevision()
    if request.method == 'POST':
        form = QuestionEditForm(request.POST, instance=question_revision)
        if form.is_valid():
            question_revision.question = question
            question_revision.editor = get_user(request)
            form.save()
            added_tags_ids = filter(None, request.POST['added_tags'].split(';'))
            tags = Tag.objects.filter(id__in=added_tags_ids)
            question_revision.tags = tags
            question_revision.save()
            url = reverse(URLS.QUESTIONS)
            return HttpResponseRedirect(url)
    else:
        question_revision.title = question.title
        question_revision.text = question.text
        if question.questionrevision_set \
                .filter(status=QuestionRevision.STATUS_AWATING_APPROVAL).count() > 0:

            prev_revision = question.questionrevision_set \
                                .filter(status=QuestionRevision.STATUS_AWATING_APPROVAL).order_by('-created')[:1][0]
            form = QuestionEditForm(instance=prev_revision)
            form.initial['editor_comment'] = ''
            tags = prev_revision.tags.all()
        else:
            form = QuestionEditForm(instance=question_revision)

    return render(request, '_questions/question_edit.html',
                  {'form': form, 'tags': tags, 'question': question, 'prev_revision': prev_revision})


@login_required
@permission_required(PERMISSION.AUTHORIZE_QUESTION_EDIT)
def authorize_question_edit(request, question_id):
    question = Question.objects.get(id=question_id)
    supervisor = get_user(request)
    revision = question.questionrevision_set.filter(status=QuestionRevision.STATUS_AWATING_APPROVAL).exclude(
        editor=supervisor).order_by('created')[:1][0]

    if not revision:
        messages.add_message(request, messages.WARNING, _('Nothing to review!'))
        return HttpResponseRedirect(URLS.QUESTIONS)

    if request.method == 'POST':
        revision_form = QuestionRevisionForm(request.POST, instance=revision)
        revision_id = request.POST['revision_id']
        if int(revision_id) == revision.id:
            url = reverse(URLS.QUESTIONS)
            revision.supervisor = supervisor
            revision_form.save()
            if 'not-approve' in request.POST:
                revision.status = QuestionRevision.STATUS_REJECTED
                revision.save()
                MessageUtil.send_message(supervisor, revision.editor, Message.TYPE_QUESTION_EDIT_DENIED,
                                         params=revision.id)
                return HttpResponseRedirect(url)

            revision.status = QuestionRevision.STATUS_APPROVED
            revision.save()

            question.title = revision.title
            question.text = revision.text
            added_tags_ids = filter(None, request.POST['added_tags'].split(';'))
            tags = Tag.objects.filter(id__in=added_tags_ids)
            question.tag_set = tags
            question.save()
            context_info = 'question_id:' + str(question.id) + ';' + 'revision_id:' + str(revision.id)
            system_user = AppUtil.get_system_user()
            AppUtil.process_transaction(user_from=system_user, user_to=supervisor,
                                        amount=MitTransaction.AMOUNT_APPROVE_QUESTION_EDIT,
                                        trans_type=MitTransaction.TYPE_APPROVE_QUESTION_EDIT,
                                        context_info=context_info)

            amount = 0
            sophistication = request.POST['sophistication']
            if sophistication == '1':
                amount = MitTransaction.AMOUNT_EDIT_QUESTION_SMALL
            elif sophistication == '2':
                amount = MitTransaction.AMOUNT_EDIT_QUESTION_MIDDLE
            elif sophistication == '3':
                amount = MitTransaction.AMOUNT_EDIT_QUESTION_FULL

            AppUtil.process_transaction(user_from=system_user, user_to=revision.editor,
                                        amount=amount,
                                        trans_type=MitTransaction.TYPE_EDIT_QUESTION,
                                        context_info=context_info)

            MessageUtil.send_message(supervisor, revision.editor, Message.TYPE_QUESTION_EDIT_AUTHORIZED,
                                     params=revision.id)

            return HttpResponseRedirect(url)
        else:
            messages.add_message(request, messages.ERROR, _('Revision already approved'))
    else:
        revision_form = QuestionRevisionForm(instance=revision)

    tags = revision.tags.all()

    return render(request, '_questions/question_revision.html',
                  {'question': question, 'revision': revision, 'form': revision_form, 'tags': tags})


@login_required
def question_add_comment(request):
    question_id = request.POST['id']
    commnet_text = request.POST['comment']
    question = Question.objects.get(id=question_id)

    user = get_user(request)
    comment = QuestionComment()
    comment.user = user
    comment.text = bleach.clean(commnet_text, tags=constants.ALLOWED_TAGS)

_questions/templates/_questions/question_edit.html
{% extends "pochopit/base.html" %}

{% load bootstrap3 %}
{% load staticfiles %}
{% load i18n %}
{% load pochopit_tags %}
{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static "_questions/css/style.css" %}">
{% endblock %}
{% block content %}
<head>
    {{ form.media }}
    <script type="text/javascript" src="{% static "tiny_mce/themes/simple2/tinymc_custom_template.js" %}" ></script>
</head>
    <div class="container">
        {% if prev_revision %}
            <div class="row">
                <div class="col-md-12">
                    <div class="yellow-alert">
                        <h4>{% blocktrans with first_name=prev_revision.editor.first_name last_name=prev_revision.editor.last_name %}This question was already edited by {{ first_name }} {{ last_name }}, but not proceesed.{% endblocktrans %}
                        </h4>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-6">
                {% if prev_revision %}
                    <h3> {% trans 'Version from' %}<a href="{% url_from_constant '_auth' 'PROFILE' prev_revision.editor_id %}">  {{ prev_revision.editor.first_name }} {{ prev_revision.editor.last_name }}</a></h3>
                {% else %}
                    <h3> {% trans 'Original version' %} </h3>
                {% endif %}
                <div class="form-group">
                    <input class="form-control" disabled="disabled" name="title" placeholder="{% trans 'Question heading' %}"
                           type="text" value="{% if prev_revision %}{{ prev_revision.title }}{% else %}{{ question.title }}{% endif %}">
                </div>
                <div class="form-group">
                    <div style="height: 318px;border: 1px solid #CCCCCC;padding: 8px;">{% if prev_revision %}{{ prev_revision.text|safe }}{% else %}{{ question.text|safe }}{% endif %}</div>
                </div>
                {% if  question.tag_set.all %}
                    <div class="form-group">
                        <div id="tag-holder">
                        {% if prev_revision %}
                            {% for tag in prev_revision.tags.all %}
                                <span id="tag-2" class="q-tag">
                                    {{ tag.title }}
                                </span>
                            {% endfor %}
                        {% else %}
                            {% for tag in question.tag_set.all %}
                                <span id="tag-2" class="q-tag">
                                    {{ tag.title }}
                                </span>
                            {% endfor %}
                        {% endif %}
                        </div>
                    </div>
                {% endif %}
                {% if prev_revision %}
                    <div class="form-group" style="margin-top: {% if prev_revision %}24{% else %}-15{% endif %}px">
                        <label class="control-label">{% trans 'Edit comment' %}</label>
                        <textarea class="form-control" cols="40" disabled="disabled" placeholder=""
                                  rows="4" title="">{{ prev_revision.editor_comment }}</textarea>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-6">
                <h3> {% trans 'Edited version' %} </h3>
                <form action="{% url_from_constant "_questions" "EDIT_QUESTION" question.id %}" method="post" class="form">
                  {% csrf_token %}
                  {% bootstrap_form form%}
                    <div class="form-group text-right">
                        <button type="submit" class="btn btn-primary">
                            {% trans "Submit for approval" %}
                        </button>
                    </div>
                    <input type="hidden" id="added_tags" name="added_tags"/>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        var selectedTags = [];
        var autoCompleteDiv = null;
        var tagHolder = $('<div/>', {id: 'tag-holder'});
        var tagInput = $('#id_tags');
        var addedTagsInput = $('#added_tags');

        tagInput.val('');
        $(document).ready(function() {
            tagInput.val('');
            tagInput.before(tagHolder);
            {% for tag in tags %}
                addTag({{ tag.id }}, '{{ tag.title }}');
            {% endfor %}
            tagInput.on('input', function() {
                if (this.value && this.value.length > 0) {
                    var that = this;
                    $.post('{% url_from_constant '_questions' 'FIND_TAGS' %}', {search: this.value, tags: addedTagsInput.val()}, function(data) {
                        if (data) {
                            if (autoCompleteDiv == null) {
                                autoCompleteDiv = $('<div/>', {id: 'tag-autocomplete'});
                                $(that).parent().append(autoCompleteDiv);
                                autoCompleteDiv.outerWidth($(that).outerWidth());
                            }
                            autoCompleteDiv.html('<ul>' + data + '</ul>');
                        }
                    });
                    $(that).focusout(function() {
                        setTimeout(function() {
                            removeAutoCompleteDiv();
                        }, 500); //todo - vymyslet jinak
                    });
                } else {
                    removeAutoCompleteDiv();
                }
            })
        });

        function removeAutoCompleteDiv() {
            if (autoCompleteDiv != null) {
                autoCompleteDiv.remove();
                autoCompleteDiv = null;
            }
        }

        function addTag(tagId, title) {
            selectedTags.push({id: tagId, title: title});
            var tagsString = '';
            selectedTags.forEach(function(tag) {
                tagsString += '<span id="tag-' + tag.id +'" class="q-tag">' + tag.title +
                        '<span class="glyphicon glyphicon-remove" onclick="removeTag(' + tag.id + ', this)"></span>' +
                        '</span>';
            });
            tagHolder.html(tagsString);
            removeAutoCompleteDiv();
            updateSelectedTags();
            tagInput.val('');
        }

        function removeTag(tagId, element) {
            $(element).parent().remove();
            var index = 0;
            var i = 0;
            selectedTags.forEach(function(tag) {
                if (tag.id == tagId) {
                    index = i;
                }
                i++;
            });
            selectedTags.splice(index, 1);
            updateSelectedTags();
        }

        function updateSelectedTags() {
            var selectedTagsString = '';
            selectedTags.forEach(function(tag) {
                selectedTagsString += tag.id + ';';
            });
            addedTagsInput.val(selectedTagsString);
        }
    </script>
{% endblock %}

_questions/templates/_questions/question_form.html
{% extends "pochopit/base.html" %}

{% load bootstrap3 %}
{% load staticfiles %}
{% load i18n %}
{% load pochopit_tags %}
{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static "_questions/css/style.css" %}">
{% endblock %}
{% block content %}
<head>
    {{ form.media }}
    <script type="text/javascript" src="{% static "tiny_mce/themes/simple2/tinymc_custom_template.js" %}" ></script>
    <script type="text/javascript" src="{% static "pretty_print/js/prettify.js" %}" ></script>
</head>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form novalidate action="{% url_from_constant "_questions" "ASK_QUESTION" %}"
                  method="post" class="form">
                  {% csrf_token %}
                  {% bootstrap_form form %}
                    <div class="form-group text-right">
                        <button type="submit" class="btn btn-primary">
                            {% trans "Ask question" %}
                        </button>
                    </div>
                    <input type="hidden" id="added_tags" name="added_tags"/>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        var selectedTags = [];
        var autoCompleteDiv = null;
        var tagHolder = $('<div/>', {id: 'tag-holder'});
        var tagInput = $('#id_tags');
        var addedTagsInput = $('#added_tags');
        var selectedIndex = -1;

        tagInput.val('');
        $(document).ready(function() {
            addedTagsInput = $('#added_tags');
            tagInput = $('#id_tags');
            tagInput.before(tagHolder);
            {% for tag in tags %}
                addTag({{ tag.id }}, '{{ tag.title }}');
            {% endfor %}
            tagInput.on('input', function() {
                if (this.value && this.value.length > 0) {
                    var that = this;
                    $.post('{% url_from_constant '_questions' 'FIND_TAGS' %}', {search: this.value, tags: addedTagsInput.val()}, function(data) {
                        if (data) {
                            if (autoCompleteDiv == null) {
                                autoCompleteDiv = $('<div/>', {id: 'tag-autocomplete'});
                                $(that).parent().append(autoCompleteDiv);
                                autoCompleteDiv.outerWidth($(that).outerWidth());
                            }
                            autoCompleteDiv.html('<ul>' + data + '</ul>');
                        }
                    });
                    $(that).focusout(function() {
                        setTimeout(function() {
                            removeAutoCompleteDiv();
                        }, 500); //todo - vymyslet jinak
                    });
                } else {
                    removeAutoCompleteDiv();
                }
            })
        });

        function removeAutoCompleteDiv() {
            if (autoCompleteDiv != null) {
                autoCompleteDiv.remove();
                autoCompleteDiv = null;
            }
            selectedIndex = 0;
        }

        function addTag(tagId, title) {
            selectedTags.push({id: tagId, title: title});
            var tagsString = '';
            selectedTags.forEach(function(tag) {
                tagsString += '<span id="tag-' + tag.id +'" class="q-tag">' + tag.title +
                        '<span class="glyphicon glyphicon-remove" onclick="removeTag(' + tag.id + ', this)"></span>' +
                        '</span>';
            });
            tagHolder.html(tagsString);
            removeAutoCompleteDiv();
            updateSelectedTags();
            tagInput.val('');
        }

        function removeTag(tagId, element) {
            $(element).parent().remove();
            var index = 0;
            var i = 0;
            selectedTags.forEach(function(tag) {
                if (tag.id == tagId) {
                    index = i;
                }
                i++;
            });
            selectedTags.splice(index, 1);
            updateSelectedTags();
        }

        function updateSelectedTags() {
            var selectedTagsString = '';
            selectedTags.forEach(function(tag) {
                selectedTagsString += tag.id + ';';
            });
            addedTagsInput.val(selectedTagsString);
        }

    document.onkeydown = checkKey;
    function checkKey(e) {
        e = e || window.event;
        if (e.keyCode == '38') {
            // up arrow
        } else if (e.keyCode == '40') {
            // down arrow
            if (autoCompleteDiv) {
                console.log(autoCompleteDiv[0]);
                autoCompleteDiv.find('ul').find('li').each(function(i) {
                    if (i == selectedIndex) {
                        $(this).addClass('active');
                    } else {

                    }
                });
            }
        } else if (e.keyCode == '30' && selectedIndex > 0) {

        }
    }
    </script>
{% endblock %}